// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RidePlanner.Infrastructure.Persistence;

#nullable disable

namespace RidePlanner.Infrastructure.Migrations
{
    [DbContext(typeof(RidePlannerDbContext))]
    [Migration("20260811142314_MakeTripStopCoordinatesNullable")]
    partial class MakeTripStopCoordinatesNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RidePlanner.Domain.Entities.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripStopId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("TripStopId")
                        .IsUnique();

                    b.ToTable("Accommodations", (string)null);
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Budget.BudgetEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccommodationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstimatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TripBudgetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId")
                        .IsUnique();

                    b.HasIndex("TripBudgetId");

                    b.ToTable("BudgetEstimates", (string)null);
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Budget.TripBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("TripBudgets", (string)null);
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Checklist.ChecklistCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("ChecklistCategories", (string)null);
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Checklist.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "DisplayOrder");

                    b.ToTable("ChecklistItems", (string)null);
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.TripStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Accommodation", b =>
                {
                    b.HasOne("Trip", "Trip")
                        .WithMany("Accommodations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RidePlanner.Domain.Entities.TripStop", "TripStop")
                        .WithOne("Accommodation")
                        .HasForeignKey("RidePlanner.Domain.Entities.Accommodation", "TripStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("TripStop");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Budget.BudgetEstimate", b =>
                {
                    b.HasOne("RidePlanner.Domain.Entities.Accommodation", "Accommodation")
                        .WithOne("BudgetEstimate")
                        .HasForeignKey("RidePlanner.Domain.Entities.Budget.BudgetEstimate", "AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RidePlanner.Domain.Entities.Budget.TripBudget", "TripBudget")
                        .WithMany("Estimates")
                        .HasForeignKey("TripBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("TripBudget");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Budget.TripBudget", b =>
                {
                    b.HasOne("Trip", "Trip")
                        .WithOne("Budget")
                        .HasForeignKey("RidePlanner.Domain.Entities.Budget.TripBudget", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Checklist.ChecklistCategory", b =>
                {
                    b.HasOne("Trip", "Trip")
                        .WithMany("ChecklistCategories")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Checklist.ChecklistItem", b =>
                {
                    b.HasOne("RidePlanner.Domain.Entities.Checklist.ChecklistCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.TripStop", b =>
                {
                    b.HasOne("Trip", "Trip")
                        .WithMany("Stops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Accommodation", b =>
                {
                    b.Navigation("BudgetEstimate");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Budget.TripBudget", b =>
                {
                    b.Navigation("Estimates");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.Checklist.ChecklistCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RidePlanner.Domain.Entities.TripStop", b =>
                {
                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("Trip", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Budget")
                        .IsRequired();

                    b.Navigation("ChecklistCategories");

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
